### ISSUE TITLE
[FEAT] 로그인 페이지 중 미비된 UI 업데이트

### ISSUE THREAD

**Issue by WhiteHyun** [PLUB2022/PLUB-iOS#103]
## 📌  Feature Issue

- 약간씩 처리되지 않은 UI 구현

## 📝  To-do

- [x] 카테고리 선택하는 구간 진입 시 `다음에 하기` 구현
- [x] 닉네임 설정 시 `OOO님 ~~~`과 같이 닉네임 언급하기
- [x] UI 패딩값 조절
