### ISSUE TITLE
[FEAT] 로그인 UX 수정

### ISSUE THREAD

**Issue by WhiteHyun** [PLUB2022/PLUB-iOS#106]
## 📌  Feature Issue

- 올바르지 않는 동작 개선

## 📝  To-do

- [x] 약관페이지가 하나만 Expandable되도록 수정
- [x] 닉네임 입력 시 키보드 높이만큼 view가 올라가게 수정
- [x] 프로필 이미지 contentMode 수정
- [x] 살짝 스와이프 할 때 index가 바뀌는 버그 수정
- [x] SE 버전 아이폰에서 버튼의 bottom이 너무 낮은 위치에 있는 것 수정
- [x] 생년월일 spinner에 제한 걸기(`오늘`까지 스핀이 되거나 오늘을 기준으로 만 14세가 되는 날까지를 설정할 수 있거나)
