### ISSUE TITLE
[FEAT] 로그인 페이지 자잘한 부분 구현

### ISSUE THREAD

**Issue by WhiteHyun** [PLUB2022/PLUB-iOS#138]
## 📌  Feature Issue

- [x] FCM 추가하기
- [ ] UI를 figma 앱 디자인에 맞추기
- [x] Cropping 지원하기
- [x] 온보딩 로직 일부 수정

## 📝  To-do

- [x] FCM Network 요청에 추가하기
- [x] Onboarding의 Lottie 뷰 크기 설정
- [ ] 약관 페이지의 버튼 크기 설정 (#18)
- [x] Crop 기능 구현 (depend on #164)
- [x] 온보딩 진입 후 로그인VC로 이동할 때 앱 최초진입 여부를 결정하도록 수정
