### ISSUE TITLE
[ADD] Firebase 초기 세팅

### ISSUE THREAD

**Issue by soobin-k** [PLUB2022/PLUB-iOS#191]
## 📌  Feature Issue
Firebase로 앱 배포를 위한 파일, 라이브러리, 코드 세팅 작업

## 📝  To-do
- [ ] GoogleService-Info 파일 추가
- [ ] Firebase SDK 추가
- [ ] 초기화 코드 추가
